'use client';

import { useState, useEffect } from 'react';
import { Role, ROLE_NAMES, ROLE_ICONS } from '@/lib/constants';

interface LeaderRoleConfiguratorProps {
  gameState: any;
  emit: (event: string, payload: any) => Promise<any>;
  setError: (err: string) => void;
}

export default function LeaderRoleConfigurator({ gameState, emit, setError }: LeaderRoleConfiguratorProps) {
  const [roles, setRoles] = useState<Role[]>([]);
  const [loading, setLoading] = useState(true);

  // When mounted, roles are generated by backend and sent via 'setup:roles-generated'
  // But since we are showing this *after* receiving 'setup:roles-generated', 
  // we actually need to intercept it in `leader/page.tsx` and pass it down.
  // Wait, `leader/page.tsx` didn't catch `setup:roles-generated` yet.
  
  // Actually, I can just recalculate the default distribution here or listen to the event globally.
  // Let's implement the generation logic locally as default, and then send the final array to `setup:roles-confirmed`.
  useEffect(() => {
    // Generate default distribution
    const playerCount = gameState.players.length;
    const totalMafia = Math.ceil(playerCount / 4);
    const totalCitizens = playerCount - totalMafia;

    const mafiaOrder = [Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR];
    const citizenOrder = [Role.SHERIFF, Role.DOCTOR, Role.SNIPER, Role.POLICEWOMAN, Role.NURSE, Role.CITIZEN];

    let generated: Role[] = [];
    
    for (let i = 0; i < totalMafia; i++) {
       generated.push(i < mafiaOrder.length - 1 ? mafiaOrder[i] : Role.MAFIA_REGULAR);
    }
    
    for (let i = 0; i < totalCitizens; i++) {
       generated.push(i < citizenOrder.length - 1 ? citizenOrder[i] : Role.CITIZEN);
    }

    setRoles(generated);
    setLoading(false);
  }, [gameState.players.length]);

  const handleRoleChange = (index: number, newRole: Role) => {
    const newRoles = [...roles];
    newRoles[index] = newRole;
    setRoles(newRoles);
  };

  const handleConfirm = async () => {
    try {
      setLoading(true);
      await emit('setup:roles-confirmed', { roomId: gameState.roomId, roles });
    } catch (err: any) {
      setError(err.message);
      setLoading(false);
    }
  };

  const allRolesList = Object.values(Role);

  if (loading) return <div className="text-center p-12 text-[#555] font-mono tracking-widest">INITIALIZING ROSTER...</div>;

  const mafiaRoles = roles.filter(r => [Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR].includes(r));
  const citizenRoles = roles.filter(r => ![Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR].includes(r));

  return (
    <div className="mb-10">
      <div className="text-center mb-8 border-b border-[#2a2a2a] pb-6">
        <h2 className="text-3xl font-black text-white" style={{ fontFamily: 'Amiri, serif' }}>إعداد الأدوار وتوزيعها</h2>
        <p className="text-[#808080] font-mono tracking-[0.2em] mt-2 uppercase text-xs">ROLE COMPOSITION MATRIX</p>
      </div>

      <div className="grid md:grid-cols-2 gap-8 mb-8">
        {/* Mafia Column */}
        <div className="noir-card p-6 border-[#8A0303]/40">
          <h3 className="text-lg font-mono text-[#8A0303] uppercase tracking-widest mb-4 border-b border-[#8A0303]/40 pb-2">
            SYNDICATE (المافيا): {mafiaRoles.length}
          </h3>
          <div className="space-y-3">
            {roles.map((r, i) => {
              const isMafia = [Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR].includes(r);
              if (!isMafia) return null;
              return (
                <div key={i} className="flex items-center gap-3 bg-[#050505] p-2 border border-[#8A0303]/20">
                  <span className="text-2xl w-8 text-center grayscale">{ROLE_ICONS[r]}</span>
                  <select 
                    value={r} 
                    onChange={(e) => handleRoleChange(i, e.target.value as Role)}
                    className="bg-[#050505] text-[#C5A059] focus:text-white font-mono text-sm w-full outline-none p-1 appearance-none border border-[#8A0303]/30 cursor-pointer"
                    style={{ WebkitAppearance: 'none', MozAppearance: 'none' }}
                  >
                    {allRolesList.map(role => (
                       <option key={role} value={role} className="bg-[#111] text-[#C5A059] font-mono py-2">
                         {ROLE_NAMES[role]} ({role})
                       </option>
                    ))}
                  </select>
                </div>
              );
            })}
          </div>
        </div>

        {/* Citizens Column */}
        <div className="noir-card p-6 border-[#2a2a2a]">
          <h3 className="text-lg font-mono text-[#C5A059] uppercase tracking-widest mb-4 border-b border-[#2a2a2a] pb-2">
            CITIZENS (المواطنون): {citizenRoles.length}
          </h3>
          <div className="space-y-3">
            {roles.map((r, i) => {
              const isMafia = [Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR].includes(r);
              if (isMafia) return null;
              return (
                <div key={i} className="flex items-center gap-3 bg-[#050505] p-2 border border-[#2a2a2a]">
                  <span className="text-2xl w-8 text-center grayscale opacity-80">{ROLE_ICONS[r]}</span>
                  <select 
                    value={r} 
                    onChange={(e) => handleRoleChange(i, e.target.value as Role)}
                    className="bg-[#050505] text-[#C5A059] focus:text-white font-mono text-sm w-full outline-none p-1 appearance-none border border-[#2a2a2a] cursor-pointer"
                    style={{ WebkitAppearance: 'none', MozAppearance: 'none' }}
                  >
                    {allRolesList.map(role => (
                       <option key={role} value={role} className="bg-[#111] text-[#C5A059] font-mono py-2">
                         {ROLE_NAMES[role]} ({role})
                       </option>
                    ))}
                  </select>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      <div className="text-center">
        <button onClick={handleConfirm} className="btn-premium px-12 py-4">
          <span className="text-white">CONFIRM COMPOSITION</span>
        </button>
      </div>

    </div>
  );
}
